package com.theiler.tmdbpeliculas.dominio;

import java.util.HashMap;
import java.util.Map;

public class Lenguajes {
    public static Map<String,String> lenguajes=new HashMap<String, String>() {{
        put("af", "africaans");
        put("af-ZA", "Afrikaans (Sudáfrica)");
        put("ar", "Arábica");
        put("ar-AE", "Árabe (EAU)");
        put("ar-BH", "Árabe (Bahrein)");
        put("ar-DZ", "Árabe (Argelia)");
        put("ar-EG", "Árabe (Egipto)");
        put("ar-IQ", "Árabe (Iraq)");
        put("ar-JO", "Árabe (Jordania)");
        put("ar-KW", "Árabe (Kuwait)");
        put("ar-LB", "Árabe (Líbano)");
        put("ar-LY", "Árabe (Libia)");
        put("ar-MA", "Árabe (Marruecos)");
        put("ar-OM", "Árabe (Omán)");
        put("ar-QA", "Árabe (Qatar)");
        put("ar-SA", "Árabe (Arabia Saudita)");
        put("ar-SY", "Árabe (Siria)");
        put("ar-TN", "Árabe (Túnez)");
        put("ar-YE", "Árabe (Yemen)");
        put("az", "Azerí (latín)");
        put("az-AZ", "Azerí (latín) (Azerbaiyán)");
        put("az-AZ", "Azerí (cirílico) (Azerbaiyán)");
        put("be", "Bielorruso");
        put("be-BY", "Bielorruso (Bielorrusia)");
        put("bg", "búlgaro");
        put("bg-BG", "Búlgaro (Bulgaria)");
        put("bs-BA", "Bosnio (Bosnia y Herzegovina)");
        put("ca", "catalán");
        put("ca-ES", "Catalán (españa)");
        put("cs", "checo");
        put("cs-CZ", "Checo (república checa)");
        put("cy", "galés");
        put("cy-GB", "Galés (Reino Unido)");
        put("da", "danés");
        put("da-DK", "Danés (Dinamarca)");
        put("de", "alemán");
        put("de-AT", "Alemán (Austria)");
        put("de-CH", "Alemán (Suiza)");
        put("de-DE", "Alemán Alemania)");
        put("de-LI", "Alemán (Liechtenstein)");
        put("de-LU", "Alemán (Luxemburgo)");
        put("dv", "Divehi");
        put("dv-MV", "Divehi (Maldivas)");
        put("el", "griego");
        put("el-GR", "Griego (grecia)");
        put("en", "Inglés");
        put("en-AU", "Inglés (Australia)");
        put("en-BZ", "Inglés (belice)");
        put("en-CA", "Inglés (Canadá)");
        put("en-CB", "Inglés (caribe)");
        put("en-GB", "Inglés reino unido)");
        put("en-IE", "Inglés (Irlanda)");
        put("en-JM", "Inglés (Jamaica)");
        put("en-NZ", "Inglés (Nueva Zelanda)");
        put("en-PH", "Inglés (República de Filipinas)");
        put("en-TT", "Inglés (Trinidad y Tobago)");
        put("en-US", "Inglés Estados Unidos)");
        put("en-ZA", "Inglés (Sudáfrica)");
        put("en-ZW", "Inglés (Zimbabwe)");
        put("eo", "Esperanto");
        put("es", "Español");
        put("es-AR", "Español (argentina)");
        put("es-BO", "Español (bolivia)");
        put("es-CL", "Español (chile)");
        put("es-CO", "Español (colombia)");
        put("es-CR", "Español (Costa Rica)");
        put("es-DO", "Español (Republica Dominicana)");
        put("es-EC", "Español (ecuador)");
        put("es-ES", "Español (castellano)");
        put("es-ES", "Español");
        put("es-GT", "Español (guatemala)");
        put("es-HN", "Español (honduras)");
        put("es-MX", "Español (mexico)");
        put("es-NI", "Español (nicaragua)");
        put("es-PA", "Español (Panamá)");
        put("es-PE", "Español (Perú)");
        put("es-PR", "Español (Puerto Rico)");
        put("es-PY", "Español (Paraguay)");
        put("es-SV", "Spanish (El Salvador)");
        put("es-UY", "Español (uruguay)");
        put("es-VE", "Español (venezuela)");
        put("et", "Estonio");
        put("et-EE", "Estonio (Estonia)");
        put("eu", "vasco");
        put("eu-ES", "Vasco (españa)");
        put("fa", "Farsi");
        put("fa-IR", "Farsi (Irán)");
        put("fi", "finlandés");
        put("fi-FI", "Finlandés (Finlandia)");
        put("fo", "faroese");
        put("fo-FO", "Feroés (Islas Feroe)");
        put("fr", "francés");
        put("fr-BE", "Francés (bélgica)");
        put("fr-CA", "Francés (Canadá)");
        put("fr-CH", "Francés (Suiza)");
        put("fr-FR", "Francés Francia)");
        put("fr-LU", "Francés (Luxemburgo)");
        put("fr-MC", "Francés (Principado de Mónaco)");
        put("gl", "gallego");
        put("gl-ES", "Gallego");
        put("gu", "Gujarati");
        put("gu-IN", "Gujarati (India)");
        put("he", "hebreo");
        put("he-IL", "Hebreo (Israel)");
        put("hi", "No");
        put("hi-IN", "Hindi (India)");
        put("hr", "croata");
        put("hr-BA", "Croata (Bosnia y Herzegovina)");
        put("hr-HR", "Croata (Croacia)");
        put("hu", "húngaro");
        put("hu-HU", "Húngaro (Hungría)");
        put("hy", "armenio");
        put("hy-AM", "Armenio (Armenia)");
        put("id", "indonesio");
        put("id-ID", "Indonesio (indonesio)");
        put("is", "islandés");
        put("is-IS", "Islandés (Islandia)");
        put("it", "italiano");
        put("it-CH", "Italiano (Suiza)");
        put("it-IT", "Italiano (italia)");
        put("ja", "japonés");
        put("ja-JP", "Japonés (Japón)");
        put("ka", "georgiano");
        put("ka-GE", "Georgiano (Georgia)");
        put("kk", "Kazajo");
        put("kk-KZ", "Kazajo");
        put("kn", "Kannada");
        put("kn-IN", "Kannada (India)");
        put("ko", "coreano");
        put("ko-KR", "Coreano (Corea)");
        put("kok", "Konkani");
        put("kok-IN", "Konkani (India)");
        put("ky", "Kirguís");
        put("ky-KG", "Kirguistán (Kirguistán)");
        put("lt", "lituano");
        put("lt-LT", "Lituano (Lituania)");
        put("lv", "letón");
        put("lv-LV", "Letón (Letonia)");
        put("mi", "maorí");
        put("mi-NZ", "Maorí (Nueva Zelanda)");
        put("mk", "Macedonia Macedonia");
        put("mk-MK", "ARY Macedonia (Antigua República Yugoslava de Macedonia)");
        put("mn", "mongol");
        put("mn-MN", "Mongol (mongolia)");
        put("mr", "Marathi");
        put("mr-IN", "Marathi (India)");
        put("ms", "malayo");
        put("ms-BN", "Malayo (Brunei Darussalam)");
        put("ms-MY", "Malayo (Malasia");
        put("mt", "maltés");
        put("mt-MT", "Maltés (Malta)");
        put("nb", "Noruego (Bokm? L)");
        put("nb-NO", "Noruego (Bokm? L) (Noruega)");
        put("nl", "holandés");
        put("nl-BE", "Holandés (Bélgica)");
        put("nl-NL", "Holandés (Países Bajos)");
        put("nn-NO", "Noruego (Nynorsk) (Noruega)");
        put("ns", "Sotho del norte");
        put("ns-ZA", "Sotho septentrional (Sudáfrica)");
        put("pa", "punjabi");
        put("pa-IN", "Punjabi (India)");
        put("pl", "polaco");
        put("pl-PL", "Polaco (Polonia)");
        put("ps", "Pashto");
        put("ps-AR", "Pashto (Afganistán)");
        put("pt", "portugués");
        put("pt-BR", "Portugués (Brasil)");
        put("pt-PT", "Portugués (portugal)");
        put("qu", "Quechua");
        put("qu-BO", "Quechua (Bolivia)");
        put("qu-EC", "Quechua (Ecuador)");
        put("qu-PE", "Quechua (Peru)");
        put("ro", "rumano");
        put("ro-RO", "Rumano (Rumania)");
        put("ru", "ruso");
        put("ru-RU", "Ruso (Rusia)");
        put("sa", "sánscrito");
        put("sa-IN", "Sánscrito (India)");
        put("se", "Sami (norteño)");
        put("se-FI", "Sami (Norte) (Finlandia)");
        put("se-FI", "Sami (Skolt) (Finlandia)");
        put("se-FI", "Sami (Inari) (Finlandia)");
        put("se-NO", "Sami (Norte) (Noruega)");
        put("se-NO", "Sami (Flor) (Noruega)");
        put("se-NO", "Sami (sur) (Noruega)");
        put("se-SE", "Sami (Norte) (Suecia)");
        put("se-SE", "Sami (Flor) (Suecia)");
        put("se-SE", "Sami (sur) (Suecia)");
        put("sk", "eslovaco");
        put("sk-SK", "Eslovaco (Eslovaquia)");
        put("sl", "esloveno");
        put("sl-SI", "Esloveno");
        put("sq", "albanés");
        put("sq-AL", "Albanés (albanés)");
        put("sr-BA", "Serbio (latino) (Bosnia y Herzegovina)");
        put("sr-BA", "Serbio (cirílico) (Bosnia y Herzegovina)");
        put("sr-SP", "Serbio (latino) (Serbia y Montenegro)");
        put("sr-SP", "Serbio (cirílico) (Serbia y Montenegro)");
        put("sv", "sueco");
        put("sv-FI", "Sueco (Finlandia)");
        put("sv-SE", "Sueco (Suecia)");
        put("sw", "Ingles");
        put("sw-KE", "Inglés (Kenia)");
        put("syr", "Siríaco");
        put("syr-SY", "Siríaco (Siria)");
        put("ta", "Tamil");
        put("ta-IN", "Tamil (India)");
        put("te", "Telugu");
        put("te-IN", "Telugu (India)");
        put("th", "tailandés");
        put("th-TH", "Tailandés (Tailandia)");
        put("tl", "Tagalo");
        put("tl-PH", "Tagalo (Filipinas)");
        put("tn", "Tswana");
        put("tn-ZA", "Tswana (Sudáfrica)");
        put("tr", "turco");
        put("tr-TR", "Turco (Turquía)");
        put("tt", "sarro");
        put("tt-RU", "Tártaro (Rusia)");
        put("ts", "Tsonga");
        put("uk", "ucranio");
        put("uk-UA", "Ucraniano (Ucrania)");
        put("ur", "Urdu");
        put("ur-PK", "Urdu (República Islámica de Pakistán)");
        put("uz", "Uzbeco (latín)");
        put("uz-UZ", "Uzbeco (latino) (Uzbekistán)");
        put("uz-UZ", "Uzbeco (cirílico) (Uzbekistán)");
        put("vi", "vietnamita");
        put("vi-VN", "Vietnamita (vietnamita)");
        put("xh", "Xhosa");
        put("xh-ZA", "Xhosa (Sudáfrica)");
        put("zh", "chino");
        put("zh-CN", "Chino (s)");
        put("zh-HK", "Chino (Hong Kong)");
        put("zh-MO", "Chino (Macao)");
        put("zh-SG", "Chino (singapur)");
        put("zh-TW", "Chino (T)");
        put("zu", "zulú");
        put("zu-ZA", "Zulu (Sudáfrica)");

    }};

    public static String get(String originalLanguage) {
        String l=lenguajes.get(originalLanguage);
        if(l==null){return "";}
        return l.substring(0,1).toUpperCase()+l.substring(1).toLowerCase();
    }
}
